[tool.poetry]
name = "sanic"
version = "21.12.1"
description = "Next generation Python web server/framework | Build fast. Run fast."
authors = [ "Sanic Community Organization <info@opencollective.com>",]
homepage = "https://sanic.dev/"
repository = "https://github.com/sanic-org/sanic"
documentation = "https://sanic.dev/en/guide/"
readme = "README.rst"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
setuptools = "^60.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
